# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Add remote host key to known_hosts
        run: |
          mkdir ~/.ssh
          ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
      
      - name: Add SSH key
        run: |
            echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/private_key
            chmod 600 ~/.ssh/private_key

      - name: Calculate SHA256 of <username>@<hostname> secrets to allow verification
        run: |
            echo "This is the sha256 for <username>@<hostname>, verify by running \`echo -n \"<username>@<hostname>\" | shasum -a 256\` locally"
            echo -n "${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}" | shasum -a 256

      - name: Attempt SFTP connection
        run: |
          sftp -v -v -v -oBatchMode=yes -i ~/.ssh/private_key ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}
